apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      author: prakash
  template:
    metadata:
      labels:                           #labels should match with matchLabels
        app: nginx
        author: prakash
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynginxapp-service
spec:
  selector:                       #should match with Deployment's template label
    app: nginx
    author: prakash
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000  
  type: NodePort
  
  
  
  
  
  
  
  
#vim deployment.yaml
#vim service.yaml
#kubectl apply -f deployment.yaml
#kubectl get deployment
#kubectl get pods -o wide
#kubectl apply -f service.yaml
#kubectl get services
#kubectl get pods -o wide